'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'このソース コードは Microsoft.VSDesigner、バージョン 4.0.30319.42000 によって自動生成されました。
'
Namespace SYHANJAG00SYHANJAW00
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SYHANJAW00Soap", [Namespace]:="http://tempuri.org/SYHANJAW00/SYHANJAW00")>  _
    Partial Public Class SYHANJAW00
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private mExecOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://knapsv/JPGAP/SY/SYHANJAW/SYHANJAW00/SYHANJAW00.asmx"
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event mExecCompleted As mExecCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SYHANJAW00/SYHANJAW00/mExec", RequestNamespace:="http://tempuri.org/SYHANJAW00/SYHANJAW00", ResponseNamespace:="http://tempuri.org/SYHANJAW00/SYHANJAW00", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function mExec(ByVal pstrKENCD As String, ByVal pstrTRGDATE As String, ByVal pstrSYUFROM As String, ByVal pstrSYUTO As String, ByVal pstrMOT_TRGDATE As String, ByVal pstrMOT_SYUFROM As String) As String
            Dim results() As Object = Me.Invoke("mExec", New Object() {pstrKENCD, pstrTRGDATE, pstrSYUFROM, pstrSYUTO, pstrMOT_TRGDATE, pstrMOT_SYUFROM})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginmExec(ByVal pstrKENCD As String, ByVal pstrTRGDATE As String, ByVal pstrSYUFROM As String, ByVal pstrSYUTO As String, ByVal pstrMOT_TRGDATE As String, ByVal pstrMOT_SYUFROM As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("mExec", New Object() {pstrKENCD, pstrTRGDATE, pstrSYUFROM, pstrSYUTO, pstrMOT_TRGDATE, pstrMOT_SYUFROM}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndmExec(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub mExecAsync(ByVal pstrKENCD As String, ByVal pstrTRGDATE As String, ByVal pstrSYUFROM As String, ByVal pstrSYUTO As String, ByVal pstrMOT_TRGDATE As String, ByVal pstrMOT_SYUFROM As String)
            Me.mExecAsync(pstrKENCD, pstrTRGDATE, pstrSYUFROM, pstrSYUTO, pstrMOT_TRGDATE, pstrMOT_SYUFROM, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub mExecAsync(ByVal pstrKENCD As String, ByVal pstrTRGDATE As String, ByVal pstrSYUFROM As String, ByVal pstrSYUTO As String, ByVal pstrMOT_TRGDATE As String, ByVal pstrMOT_SYUFROM As String, ByVal userState As Object)
            If (Me.mExecOperationCompleted Is Nothing) Then
                Me.mExecOperationCompleted = AddressOf Me.OnmExecOperationCompleted
            End If
            Me.InvokeAsync("mExec", New Object() {pstrKENCD, pstrTRGDATE, pstrSYUFROM, pstrSYUTO, pstrMOT_TRGDATE, pstrMOT_SYUFROM}, Me.mExecOperationCompleted, userState)
        End Sub
        
        Private Sub OnmExecOperationCompleted(ByVal arg As Object)
            If (Not (Me.mExecCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent mExecCompleted(Me, New mExecCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")>  _
    Public Delegate Sub mExecCompletedEventHandler(ByVal sender As Object, ByVal e As mExecCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class mExecCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
