'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'このソース コードは Microsoft.VSDesigner、バージョン 4.0.30319.42000 によって自動生成されました。
'
Namespace SDSYUJAG00SDSYUJAW00
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SDSYUJAW00Soap", [Namespace]:="http://tempuri.org/SDSYUJAW00/Service1")>  _
    Partial Public Class SDSYUJAW00
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private mSetOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://knapsv/JPGAP/SD/SDSYUJAW/SDSYUJAW00/SDSYUJAW00.asmx"
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event mSetCompleted As mSetCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SDSYUJAW00/Service1/mSet", RequestNamespace:="http://tempuri.org/SDSYUJAW00/Service1", ResponseNamespace:="http://tempuri.org/SDSYUJAW00/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function mSet( _
                    ByVal pstrKANSCD As String,  _
                    ByVal pstrSYONO As String,  _
                    ByVal pstrKBN As String,  _
                    ByVal pstrTSTANCD As String,  _
                    ByVal pstrTSTANNM As String,  _
                    ByVal pstrSTD_CD As String,  _
                    ByVal pstrSTD_KYOTEN_CD As String,  _
                    ByVal pstrSYUTDTNM As String,  _
                    ByVal pstrSIJIYMD As String,  _
                    ByVal pstrSIJITIME As String,  _
                    ByVal pstrSDYMD As String,  _
                    ByVal pstrSDTIME As String,  _
                    ByVal pstrTYAKYMD As String,  _
                    ByVal pstrTYAKTIME As String,  _
                    ByVal pstrSYOKANYMD As String,  _
                    ByVal pstrSYOKANTIME As String,  _
                    ByVal pstrAITCD As String,  _
                    ByVal pstrMETHEIKAKU As String,  _
                    ByVal pstrRUSUHARI As String,  _
                    ByVal pstrKIGCD As String,  _
                    ByVal pstrSADCD As String,  _
                    ByVal pstrASECD As String,  _
                    ByVal pstrSTACD As String,  _
                    ByVal pstrFKICD As String,  _
                    ByVal pstrJAKENREN As String,  _
                    ByVal pstrRENTIME As String,  _
                    ByVal pstrKIGTAIYO As String,  _
                    ByVal pstrGASMUMU As String,  _
                    ByVal pstrORGENIN As String,  _
                    ByVal pstrHAIKAN As String,  _
                    ByVal pstrGASGUMU As String,  _
                    ByVal pstrHOSKOKAN As String,  _
                    ByVal pstrMETYOINA As String,  _
                    ByVal pstrTYOUYOINA As String,  _
                    ByVal pstrVALYOINA As String,  _
                    ByVal pstrKYUHAIUMU As String,  _
                    ByVal pstrCOYOINA As String,  _
                    ByVal pstrSDTBIK2 As String,  _
                    ByVal pstrSNTTOKKI As String,  _
                    ByVal pstrSDTBIK3 As String,  _
                    ByVal pstrMETFUKKI As String,  _
                    ByVal pstrHOAN As String,  _
                    ByVal pstrGASGIRE As String,  _
                    ByVal pstrKIGKOSYO As String,  _
                    ByVal pstrCSNTGEN As String,  _
                    ByVal pstrCSNTNGAS As String,  _
                    ByVal pstrSDTBIK1 As String,  _
                    ByVal pstrADD_DATE As String,  _
                    ByVal pstrEDT_DATE As String,  _
                    ByVal pstrTIME As String) As String
            Dim results() As Object = Me.Invoke("mSet", New Object() {pstrKANSCD, pstrSYONO, pstrKBN, pstrTSTANCD, pstrTSTANNM, pstrSTD_CD, pstrSTD_KYOTEN_CD, pstrSYUTDTNM, pstrSIJIYMD, pstrSIJITIME, pstrSDYMD, pstrSDTIME, pstrTYAKYMD, pstrTYAKTIME, pstrSYOKANYMD, pstrSYOKANTIME, pstrAITCD, pstrMETHEIKAKU, pstrRUSUHARI, pstrKIGCD, pstrSADCD, pstrASECD, pstrSTACD, pstrFKICD, pstrJAKENREN, pstrRENTIME, pstrKIGTAIYO, pstrGASMUMU, pstrORGENIN, pstrHAIKAN, pstrGASGUMU, pstrHOSKOKAN, pstrMETYOINA, pstrTYOUYOINA, pstrVALYOINA, pstrKYUHAIUMU, pstrCOYOINA, pstrSDTBIK2, pstrSNTTOKKI, pstrSDTBIK3, pstrMETFUKKI, pstrHOAN, pstrGASGIRE, pstrKIGKOSYO, pstrCSNTGEN, pstrCSNTNGAS, pstrSDTBIK1, pstrADD_DATE, pstrEDT_DATE, pstrTIME})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginmSet( _
                    ByVal pstrKANSCD As String,  _
                    ByVal pstrSYONO As String,  _
                    ByVal pstrKBN As String,  _
                    ByVal pstrTSTANCD As String,  _
                    ByVal pstrTSTANNM As String,  _
                    ByVal pstrSTD_CD As String,  _
                    ByVal pstrSTD_KYOTEN_CD As String,  _
                    ByVal pstrSYUTDTNM As String,  _
                    ByVal pstrSIJIYMD As String,  _
                    ByVal pstrSIJITIME As String,  _
                    ByVal pstrSDYMD As String,  _
                    ByVal pstrSDTIME As String,  _
                    ByVal pstrTYAKYMD As String,  _
                    ByVal pstrTYAKTIME As String,  _
                    ByVal pstrSYOKANYMD As String,  _
                    ByVal pstrSYOKANTIME As String,  _
                    ByVal pstrAITCD As String,  _
                    ByVal pstrMETHEIKAKU As String,  _
                    ByVal pstrRUSUHARI As String,  _
                    ByVal pstrKIGCD As String,  _
                    ByVal pstrSADCD As String,  _
                    ByVal pstrASECD As String,  _
                    ByVal pstrSTACD As String,  _
                    ByVal pstrFKICD As String,  _
                    ByVal pstrJAKENREN As String,  _
                    ByVal pstrRENTIME As String,  _
                    ByVal pstrKIGTAIYO As String,  _
                    ByVal pstrGASMUMU As String,  _
                    ByVal pstrORGENIN As String,  _
                    ByVal pstrHAIKAN As String,  _
                    ByVal pstrGASGUMU As String,  _
                    ByVal pstrHOSKOKAN As String,  _
                    ByVal pstrMETYOINA As String,  _
                    ByVal pstrTYOUYOINA As String,  _
                    ByVal pstrVALYOINA As String,  _
                    ByVal pstrKYUHAIUMU As String,  _
                    ByVal pstrCOYOINA As String,  _
                    ByVal pstrSDTBIK2 As String,  _
                    ByVal pstrSNTTOKKI As String,  _
                    ByVal pstrSDTBIK3 As String,  _
                    ByVal pstrMETFUKKI As String,  _
                    ByVal pstrHOAN As String,  _
                    ByVal pstrGASGIRE As String,  _
                    ByVal pstrKIGKOSYO As String,  _
                    ByVal pstrCSNTGEN As String,  _
                    ByVal pstrCSNTNGAS As String,  _
                    ByVal pstrSDTBIK1 As String,  _
                    ByVal pstrADD_DATE As String,  _
                    ByVal pstrEDT_DATE As String,  _
                    ByVal pstrTIME As String,  _
                    ByVal callback As System.AsyncCallback,  _
                    ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("mSet", New Object() {pstrKANSCD, pstrSYONO, pstrKBN, pstrTSTANCD, pstrTSTANNM, pstrSTD_CD, pstrSTD_KYOTEN_CD, pstrSYUTDTNM, pstrSIJIYMD, pstrSIJITIME, pstrSDYMD, pstrSDTIME, pstrTYAKYMD, pstrTYAKTIME, pstrSYOKANYMD, pstrSYOKANTIME, pstrAITCD, pstrMETHEIKAKU, pstrRUSUHARI, pstrKIGCD, pstrSADCD, pstrASECD, pstrSTACD, pstrFKICD, pstrJAKENREN, pstrRENTIME, pstrKIGTAIYO, pstrGASMUMU, pstrORGENIN, pstrHAIKAN, pstrGASGUMU, pstrHOSKOKAN, pstrMETYOINA, pstrTYOUYOINA, pstrVALYOINA, pstrKYUHAIUMU, pstrCOYOINA, pstrSDTBIK2, pstrSNTTOKKI, pstrSDTBIK3, pstrMETFUKKI, pstrHOAN, pstrGASGIRE, pstrKIGKOSYO, pstrCSNTGEN, pstrCSNTNGAS, pstrSDTBIK1, pstrADD_DATE, pstrEDT_DATE, pstrTIME}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndmSet(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub mSetAsync( _
                    ByVal pstrKANSCD As String,  _
                    ByVal pstrSYONO As String,  _
                    ByVal pstrKBN As String,  _
                    ByVal pstrTSTANCD As String,  _
                    ByVal pstrTSTANNM As String,  _
                    ByVal pstrSTD_CD As String,  _
                    ByVal pstrSTD_KYOTEN_CD As String,  _
                    ByVal pstrSYUTDTNM As String,  _
                    ByVal pstrSIJIYMD As String,  _
                    ByVal pstrSIJITIME As String,  _
                    ByVal pstrSDYMD As String,  _
                    ByVal pstrSDTIME As String,  _
                    ByVal pstrTYAKYMD As String,  _
                    ByVal pstrTYAKTIME As String,  _
                    ByVal pstrSYOKANYMD As String,  _
                    ByVal pstrSYOKANTIME As String,  _
                    ByVal pstrAITCD As String,  _
                    ByVal pstrMETHEIKAKU As String,  _
                    ByVal pstrRUSUHARI As String,  _
                    ByVal pstrKIGCD As String,  _
                    ByVal pstrSADCD As String,  _
                    ByVal pstrASECD As String,  _
                    ByVal pstrSTACD As String,  _
                    ByVal pstrFKICD As String,  _
                    ByVal pstrJAKENREN As String,  _
                    ByVal pstrRENTIME As String,  _
                    ByVal pstrKIGTAIYO As String,  _
                    ByVal pstrGASMUMU As String,  _
                    ByVal pstrORGENIN As String,  _
                    ByVal pstrHAIKAN As String,  _
                    ByVal pstrGASGUMU As String,  _
                    ByVal pstrHOSKOKAN As String,  _
                    ByVal pstrMETYOINA As String,  _
                    ByVal pstrTYOUYOINA As String,  _
                    ByVal pstrVALYOINA As String,  _
                    ByVal pstrKYUHAIUMU As String,  _
                    ByVal pstrCOYOINA As String,  _
                    ByVal pstrSDTBIK2 As String,  _
                    ByVal pstrSNTTOKKI As String,  _
                    ByVal pstrSDTBIK3 As String,  _
                    ByVal pstrMETFUKKI As String,  _
                    ByVal pstrHOAN As String,  _
                    ByVal pstrGASGIRE As String,  _
                    ByVal pstrKIGKOSYO As String,  _
                    ByVal pstrCSNTGEN As String,  _
                    ByVal pstrCSNTNGAS As String,  _
                    ByVal pstrSDTBIK1 As String,  _
                    ByVal pstrADD_DATE As String,  _
                    ByVal pstrEDT_DATE As String,  _
                    ByVal pstrTIME As String)
            Me.mSetAsync(pstrKANSCD, pstrSYONO, pstrKBN, pstrTSTANCD, pstrTSTANNM, pstrSTD_CD, pstrSTD_KYOTEN_CD, pstrSYUTDTNM, pstrSIJIYMD, pstrSIJITIME, pstrSDYMD, pstrSDTIME, pstrTYAKYMD, pstrTYAKTIME, pstrSYOKANYMD, pstrSYOKANTIME, pstrAITCD, pstrMETHEIKAKU, pstrRUSUHARI, pstrKIGCD, pstrSADCD, pstrASECD, pstrSTACD, pstrFKICD, pstrJAKENREN, pstrRENTIME, pstrKIGTAIYO, pstrGASMUMU, pstrORGENIN, pstrHAIKAN, pstrGASGUMU, pstrHOSKOKAN, pstrMETYOINA, pstrTYOUYOINA, pstrVALYOINA, pstrKYUHAIUMU, pstrCOYOINA, pstrSDTBIK2, pstrSNTTOKKI, pstrSDTBIK3, pstrMETFUKKI, pstrHOAN, pstrGASGIRE, pstrKIGKOSYO, pstrCSNTGEN, pstrCSNTNGAS, pstrSDTBIK1, pstrADD_DATE, pstrEDT_DATE, pstrTIME, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub mSetAsync( _
                    ByVal pstrKANSCD As String,  _
                    ByVal pstrSYONO As String,  _
                    ByVal pstrKBN As String,  _
                    ByVal pstrTSTANCD As String,  _
                    ByVal pstrTSTANNM As String,  _
                    ByVal pstrSTD_CD As String,  _
                    ByVal pstrSTD_KYOTEN_CD As String,  _
                    ByVal pstrSYUTDTNM As String,  _
                    ByVal pstrSIJIYMD As String,  _
                    ByVal pstrSIJITIME As String,  _
                    ByVal pstrSDYMD As String,  _
                    ByVal pstrSDTIME As String,  _
                    ByVal pstrTYAKYMD As String,  _
                    ByVal pstrTYAKTIME As String,  _
                    ByVal pstrSYOKANYMD As String,  _
                    ByVal pstrSYOKANTIME As String,  _
                    ByVal pstrAITCD As String,  _
                    ByVal pstrMETHEIKAKU As String,  _
                    ByVal pstrRUSUHARI As String,  _
                    ByVal pstrKIGCD As String,  _
                    ByVal pstrSADCD As String,  _
                    ByVal pstrASECD As String,  _
                    ByVal pstrSTACD As String,  _
                    ByVal pstrFKICD As String,  _
                    ByVal pstrJAKENREN As String,  _
                    ByVal pstrRENTIME As String,  _
                    ByVal pstrKIGTAIYO As String,  _
                    ByVal pstrGASMUMU As String,  _
                    ByVal pstrORGENIN As String,  _
                    ByVal pstrHAIKAN As String,  _
                    ByVal pstrGASGUMU As String,  _
                    ByVal pstrHOSKOKAN As String,  _
                    ByVal pstrMETYOINA As String,  _
                    ByVal pstrTYOUYOINA As String,  _
                    ByVal pstrVALYOINA As String,  _
                    ByVal pstrKYUHAIUMU As String,  _
                    ByVal pstrCOYOINA As String,  _
                    ByVal pstrSDTBIK2 As String,  _
                    ByVal pstrSNTTOKKI As String,  _
                    ByVal pstrSDTBIK3 As String,  _
                    ByVal pstrMETFUKKI As String,  _
                    ByVal pstrHOAN As String,  _
                    ByVal pstrGASGIRE As String,  _
                    ByVal pstrKIGKOSYO As String,  _
                    ByVal pstrCSNTGEN As String,  _
                    ByVal pstrCSNTNGAS As String,  _
                    ByVal pstrSDTBIK1 As String,  _
                    ByVal pstrADD_DATE As String,  _
                    ByVal pstrEDT_DATE As String,  _
                    ByVal pstrTIME As String,  _
                    ByVal userState As Object)
            If (Me.mSetOperationCompleted Is Nothing) Then
                Me.mSetOperationCompleted = AddressOf Me.OnmSetOperationCompleted
            End If
            Me.InvokeAsync("mSet", New Object() {pstrKANSCD, pstrSYONO, pstrKBN, pstrTSTANCD, pstrTSTANNM, pstrSTD_CD, pstrSTD_KYOTEN_CD, pstrSYUTDTNM, pstrSIJIYMD, pstrSIJITIME, pstrSDYMD, pstrSDTIME, pstrTYAKYMD, pstrTYAKTIME, pstrSYOKANYMD, pstrSYOKANTIME, pstrAITCD, pstrMETHEIKAKU, pstrRUSUHARI, pstrKIGCD, pstrSADCD, pstrASECD, pstrSTACD, pstrFKICD, pstrJAKENREN, pstrRENTIME, pstrKIGTAIYO, pstrGASMUMU, pstrORGENIN, pstrHAIKAN, pstrGASGUMU, pstrHOSKOKAN, pstrMETYOINA, pstrTYOUYOINA, pstrVALYOINA, pstrKYUHAIUMU, pstrCOYOINA, pstrSDTBIK2, pstrSNTTOKKI, pstrSDTBIK3, pstrMETFUKKI, pstrHOAN, pstrGASGIRE, pstrKIGKOSYO, pstrCSNTGEN, pstrCSNTNGAS, pstrSDTBIK1, pstrADD_DATE, pstrEDT_DATE, pstrTIME}, Me.mSetOperationCompleted, userState)
        End Sub
        
        Private Sub OnmSetOperationCompleted(ByVal arg As Object)
            If (Not (Me.mSetCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent mSetCompleted(Me, New mSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")>  _
    Public Delegate Sub mSetCompletedEventHandler(ByVal sender As Object, ByVal e As mSetCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class mSetCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
