'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'このソース コードは Microsoft.VSDesigner、バージョン 4.0.30319.42000 によって自動生成されました。
'
Namespace MSHAGJAG00MSHAGJAW00
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="MSHAGJAW00Soap", [Namespace]:="http://tempuri.org/MSHAGJAW00/Service1")>  _
    Partial Public Class MSHAGJAW00
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private mSetExOperationCompleted As System.Threading.SendOrPostCallback
        
        Private mSetMASTEROperationCompleted As System.Threading.SendOrPostCallback
        
        Private mCSVOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.MSHAGJAG00.My.MySettings.Default.MSHAGJAG00_MSHAGJAG00MSHAGJAW00_MSHAGJAW00
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event mSetExCompleted As mSetExCompletedEventHandler
        
        '''<remarks/>
        Public Event mSetMASTERCompleted As mSetMASTERCompletedEventHandler
        
        '''<remarks/>
        Public Event mCSVCompleted As mCSVCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MSHAGJAW00/Service1/mSetEx", RequestNamespace:="http://tempuri.org/MSHAGJAW00/Service1", ResponseNamespace:="http://tempuri.org/MSHAGJAW00/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function mSetEx(ByVal pintMODE As Integer, ByVal pstrTARGET() As String, ByVal pstrGROUPCD() As String, ByVal pstrGROUPNM() As String, ByVal pstrHANJIGYOSYANM() As String, ByVal pstrBIKO() As String, ByVal pstrINS_DATE() As String, ByVal pstrINS_USER() As String, ByVal pstrUPD_DATE() As String, ByVal pstrUPD_USER() As String, ByVal pstrUSERNM As String) As String
            Dim results() As Object = Me.Invoke("mSetEx", New Object() {pintMODE, pstrTARGET, pstrGROUPCD, pstrGROUPNM, pstrHANJIGYOSYANM, pstrBIKO, pstrINS_DATE, pstrINS_USER, pstrUPD_DATE, pstrUPD_USER, pstrUSERNM})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginmSetEx(ByVal pintMODE As Integer, ByVal pstrTARGET() As String, ByVal pstrGROUPCD() As String, ByVal pstrGROUPNM() As String, ByVal pstrHANJIGYOSYANM() As String, ByVal pstrBIKO() As String, ByVal pstrINS_DATE() As String, ByVal pstrINS_USER() As String, ByVal pstrUPD_DATE() As String, ByVal pstrUPD_USER() As String, ByVal pstrUSERNM As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("mSetEx", New Object() {pintMODE, pstrTARGET, pstrGROUPCD, pstrGROUPNM, pstrHANJIGYOSYANM, pstrBIKO, pstrINS_DATE, pstrINS_USER, pstrUPD_DATE, pstrUPD_USER, pstrUSERNM}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndmSetEx(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub mSetExAsync(ByVal pintMODE As Integer, ByVal pstrTARGET() As String, ByVal pstrGROUPCD() As String, ByVal pstrGROUPNM() As String, ByVal pstrHANJIGYOSYANM() As String, ByVal pstrBIKO() As String, ByVal pstrINS_DATE() As String, ByVal pstrINS_USER() As String, ByVal pstrUPD_DATE() As String, ByVal pstrUPD_USER() As String, ByVal pstrUSERNM As String)
            Me.mSetExAsync(pintMODE, pstrTARGET, pstrGROUPCD, pstrGROUPNM, pstrHANJIGYOSYANM, pstrBIKO, pstrINS_DATE, pstrINS_USER, pstrUPD_DATE, pstrUPD_USER, pstrUSERNM, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub mSetExAsync(ByVal pintMODE As Integer, ByVal pstrTARGET() As String, ByVal pstrGROUPCD() As String, ByVal pstrGROUPNM() As String, ByVal pstrHANJIGYOSYANM() As String, ByVal pstrBIKO() As String, ByVal pstrINS_DATE() As String, ByVal pstrINS_USER() As String, ByVal pstrUPD_DATE() As String, ByVal pstrUPD_USER() As String, ByVal pstrUSERNM As String, ByVal userState As Object)
            If (Me.mSetExOperationCompleted Is Nothing) Then
                Me.mSetExOperationCompleted = AddressOf Me.OnmSetExOperationCompleted
            End If
            Me.InvokeAsync("mSetEx", New Object() {pintMODE, pstrTARGET, pstrGROUPCD, pstrGROUPNM, pstrHANJIGYOSYANM, pstrBIKO, pstrINS_DATE, pstrINS_USER, pstrUPD_DATE, pstrUPD_USER, pstrUSERNM}, Me.mSetExOperationCompleted, userState)
        End Sub
        
        Private Sub OnmSetExOperationCompleted(ByVal arg As Object)
            If (Not (Me.mSetExCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent mSetExCompleted(Me, New mSetExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MSHAGJAW00/Service1/mSetMASTER", RequestNamespace:="http://tempuri.org/MSHAGJAW00/Service1", ResponseNamespace:="http://tempuri.org/MSHAGJAW00/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function mSetMASTER(ByRef cdb As CDB, ByVal pintMODE As Integer, ByVal pstrTARGET As String, ByVal pstrGROUPCD As String, ByVal pstrGROUPNM As String, ByVal pstrHANJIGYOSYANM As String, ByVal pstrBIKO As String, ByVal pstrINS_DATE As String, ByVal pstrINS_USER As String, ByVal pstrUPD_DATE As String, ByVal pstrUPD_USER As String, ByVal pstrUSERNM As String, ByVal pstrI As String) As String
            Dim results() As Object = Me.Invoke("mSetMASTER", New Object() {cdb, pintMODE, pstrTARGET, pstrGROUPCD, pstrGROUPNM, pstrHANJIGYOSYANM, pstrBIKO, pstrINS_DATE, pstrINS_USER, pstrUPD_DATE, pstrUPD_USER, pstrUSERNM, pstrI})
            cdb = CType(results(1),CDB)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginmSetMASTER(ByVal cdb As CDB, ByVal pintMODE As Integer, ByVal pstrTARGET As String, ByVal pstrGROUPCD As String, ByVal pstrGROUPNM As String, ByVal pstrHANJIGYOSYANM As String, ByVal pstrBIKO As String, ByVal pstrINS_DATE As String, ByVal pstrINS_USER As String, ByVal pstrUPD_DATE As String, ByVal pstrUPD_USER As String, ByVal pstrUSERNM As String, ByVal pstrI As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("mSetMASTER", New Object() {cdb, pintMODE, pstrTARGET, pstrGROUPCD, pstrGROUPNM, pstrHANJIGYOSYANM, pstrBIKO, pstrINS_DATE, pstrINS_USER, pstrUPD_DATE, pstrUPD_USER, pstrUSERNM, pstrI}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndmSetMASTER(ByVal asyncResult As System.IAsyncResult, ByRef cdb As CDB) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            cdb = CType(results(1),CDB)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub mSetMASTERAsync(ByVal cdb As CDB, ByVal pintMODE As Integer, ByVal pstrTARGET As String, ByVal pstrGROUPCD As String, ByVal pstrGROUPNM As String, ByVal pstrHANJIGYOSYANM As String, ByVal pstrBIKO As String, ByVal pstrINS_DATE As String, ByVal pstrINS_USER As String, ByVal pstrUPD_DATE As String, ByVal pstrUPD_USER As String, ByVal pstrUSERNM As String, ByVal pstrI As String)
            Me.mSetMASTERAsync(cdb, pintMODE, pstrTARGET, pstrGROUPCD, pstrGROUPNM, pstrHANJIGYOSYANM, pstrBIKO, pstrINS_DATE, pstrINS_USER, pstrUPD_DATE, pstrUPD_USER, pstrUSERNM, pstrI, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub mSetMASTERAsync(ByVal cdb As CDB, ByVal pintMODE As Integer, ByVal pstrTARGET As String, ByVal pstrGROUPCD As String, ByVal pstrGROUPNM As String, ByVal pstrHANJIGYOSYANM As String, ByVal pstrBIKO As String, ByVal pstrINS_DATE As String, ByVal pstrINS_USER As String, ByVal pstrUPD_DATE As String, ByVal pstrUPD_USER As String, ByVal pstrUSERNM As String, ByVal pstrI As String, ByVal userState As Object)
            If (Me.mSetMASTEROperationCompleted Is Nothing) Then
                Me.mSetMASTEROperationCompleted = AddressOf Me.OnmSetMASTEROperationCompleted
            End If
            Me.InvokeAsync("mSetMASTER", New Object() {cdb, pintMODE, pstrTARGET, pstrGROUPCD, pstrGROUPNM, pstrHANJIGYOSYANM, pstrBIKO, pstrINS_DATE, pstrINS_USER, pstrUPD_DATE, pstrUPD_USER, pstrUSERNM, pstrI}, Me.mSetMASTEROperationCompleted, userState)
        End Sub
        
        Private Sub OnmSetMASTEROperationCompleted(ByVal arg As Object)
            If (Not (Me.mSetMASTERCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent mSetMASTERCompleted(Me, New mSetMASTERCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MSHAGJAW00/Service1/mCSV", RequestNamespace:="http://tempuri.org/MSHAGJAW00/Service1", ResponseNamespace:="http://tempuri.org/MSHAGJAW00/Service1", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function mCSV(ByVal pstrSessionID As String, ByVal pstrKURACD As String, ByVal pstrGROUPCD_F As String, ByVal pstrGROUPCD_T As String) As String
            Dim results() As Object = Me.Invoke("mCSV", New Object() {pstrSessionID, pstrKURACD, pstrGROUPCD_F, pstrGROUPCD_T})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Function BeginmCSV(ByVal pstrSessionID As String, ByVal pstrKURACD As String, ByVal pstrGROUPCD_F As String, ByVal pstrGROUPCD_T As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("mCSV", New Object() {pstrSessionID, pstrKURACD, pstrGROUPCD_F, pstrGROUPCD_T}, callback, asyncState)
        End Function
        
        '''<remarks/>
        Public Function EndmCSV(ByVal asyncResult As System.IAsyncResult) As String
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub mCSVAsync(ByVal pstrSessionID As String, ByVal pstrKURACD As String, ByVal pstrGROUPCD_F As String, ByVal pstrGROUPCD_T As String)
            Me.mCSVAsync(pstrSessionID, pstrKURACD, pstrGROUPCD_F, pstrGROUPCD_T, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub mCSVAsync(ByVal pstrSessionID As String, ByVal pstrKURACD As String, ByVal pstrGROUPCD_F As String, ByVal pstrGROUPCD_T As String, ByVal userState As Object)
            If (Me.mCSVOperationCompleted Is Nothing) Then
                Me.mCSVOperationCompleted = AddressOf Me.OnmCSVOperationCompleted
            End If
            Me.InvokeAsync("mCSV", New Object() {pstrSessionID, pstrKURACD, pstrGROUPCD_F, pstrGROUPCD_T}, Me.mCSVOperationCompleted, userState)
        End Sub
        
        Private Sub OnmCSVOperationCompleted(ByVal arg As Object)
            If (Not (Me.mCSVCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent mCSVCompleted(Me, New mCSVCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/MSHAGJAW00/Service1")>  _
    Partial Public Class CDB
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")>  _
    Public Delegate Sub mSetExCompletedEventHandler(ByVal sender As Object, ByVal e As mSetExCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class mSetExCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")>  _
    Public Delegate Sub mSetMASTERCompletedEventHandler(ByVal sender As Object, ByVal e As mSetMASTERCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class mSetMASTERCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property cdb() As CDB
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),CDB)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")>  _
    Public Delegate Sub mCSVCompletedEventHandler(ByVal sender As Object, ByVal e As mCSVCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class mCSVCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
